apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: linbit-eks
  region: us-west-2
  version: "1.24"
managedNodeGroups:
- name: lb-mng-0
  launchTemplate:
    id: lt-02cc5d8e514668eea
    version: "1"
  desiredCapacity: 3
